version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    volumes:
      - .:/var/www
    ports:
      - 8000:8000
    networks:
      - app-network
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=mydatabase
      - DB_USERNAME=root
      - DB_PASSWORD=secret

  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
    networks:
      - app-network
    environment:
      - MYSQL_DATABASE=mydatabase
      - MYSQL_ROOT_PASSWORD=secret

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www
    networks:
      - app-network
    depends_on:
      - app

  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
    networks:
      - app-network

networks:
  app-network:
    driver: bridge